//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization.Common
{
    public static class Filenames
    {
        public static readonly string Default = "Localization.Common.Filenames.Default";
    }

    public static class Menu
    {
        public static readonly string File = "Localization.Common.Menu.File";
        public static readonly string Edit = "Localization.Common.Menu.Edit";
        public static readonly string View = "Localization.Common.Menu.View";
        public static readonly string Exit = "Localization.Common.Menu.Exit";
        public static readonly string OpenImage = "Localization.Common.Menu.OpenImage";
        public static readonly string About = "Localization.Common.Menu.About";
        public static readonly string ZoomIn = "Localization.Common.Menu.ZoomIn";
        public static readonly string ZoomOut = "Localization.Common.Menu.ZoomOut";
        public static readonly string FitWindow = "Localization.Common.Menu.FitWindow";
        public static readonly string Filename = "Localization.Common.Menu.Filename";
        public static readonly string StageHint = "Localization.Common.Menu.StageHint";
    }

    public static class Actions
    {
        public static readonly string Add = "Localization.Common.Actions.Add";
        public static readonly string Apply = "Localization.Common.Actions.Apply";
        public static readonly string Browse = "Localization.Common.Actions.Browse";
        public static readonly string Cancel = "Localization.Common.Actions.Cancel";
        public static readonly string CheckUpdate = "Localization.Common.Actions.CheckUpdate";
        public static readonly string Close = "Localization.Common.Actions.Close";
        public static readonly string Confirm = "Localization.Common.Actions.Confirm";
        public static readonly string Crop = "Localization.Common.Actions.Crop";
        public static readonly string Export = "Localization.Common.Actions.Export";
        public static readonly string ExportAll = "Localization.Common.Actions.ExportAll";
        public static readonly string ExportZip = "Localization.Common.Actions.ExportZip";
        public static readonly string GeneratePreview = "Localization.Common.Actions.GeneratePreview";
        public static readonly string Help = "Localization.Common.Actions.Help";
        public static readonly string OpenRepository = "Localization.Common.Actions.OpenRepository";
        public static readonly string Preview = "Localization.Common.Actions.Preview";
        public static readonly string Remove = "Localization.Common.Actions.Remove";
        public static readonly string Replace = "Localization.Common.Actions.Replace";
        public static readonly string Reset = "Localization.Common.Actions.Reset";
        public static readonly string Save = "Localization.Common.Actions.Save";
        public static readonly string SaveExport = "Localization.Common.Actions.SaveExport";
        public static readonly string SelectFile = "Localization.Common.Actions.SelectFile";
        public static readonly string SelectFolder = "Localization.Common.Actions.SelectFolder";
        public static readonly string TurnOff = "Localization.Common.Actions.TurnOff";
        public static readonly string TurnOn = "Localization.Common.Actions.TurnOn";
    }

    public static class Formats
    {
        public static readonly string Jpg = "Localization.Common.Formats.Jpg";
        public static readonly string Png = "Localization.Common.Formats.Png";
        public static readonly string Zip = "Localization.Common.Formats.Zip";
    }

    public static class Language
    {
        public static readonly string SimplifiedChinese = "Localization.Common.Language.SimplifiedChinese";
        public static readonly string TraditionalChinese = "Localization.Common.Language.TraditionalChinese";
    }

    public static class States
    {
        public static readonly string AutoSaved = "Localization.Common.States.AutoSaved";
        public static readonly string CheckingUpdate = "Localization.Common.States.CheckingUpdate";
        public static readonly string ComingSoon = "Localization.Common.States.ComingSoon";
        public static readonly string Completed = "Localization.Common.States.Completed";
        public static readonly string Disabled = "Localization.Common.States.Disabled";
        public static readonly string Enabled = "Localization.Common.States.Enabled";
        public static readonly string Failed = "Localization.Common.States.Failed";
        public static readonly string Planned = "Localization.Common.States.Planned";
        public static readonly string Processing = "Localization.Common.States.Processing";
        public static readonly string Ready = "Localization.Common.States.Ready";
        public static readonly string Selected = "Localization.Common.States.Selected";
        public static readonly string Unselected = "Localization.Common.States.Unselected";
        public static readonly string UpdateAvailable = "Localization.Common.States.UpdateAvailable";
        public static readonly string UpdateCheckFailed = "Localization.Common.States.UpdateCheckFailed";
        public static readonly string UpToDate = "Localization.Common.States.UpToDate";
        public static readonly string Waiting = "Localization.Common.States.Waiting";
    }

    public static class Theme
    {
        public static readonly string Dark = "Localization.Common.Theme.Dark";
        public static readonly string Light = "Localization.Common.Theme.Light";
        public static readonly string System = "Localization.Common.Theme.System";
    }
}

namespace Localization.Shell
{
    public static class Navigation
    {
        public static readonly string BatchProcessing = "Localization.Shell.Navigation.BatchProcessing";
        public static readonly string ComingSoon = "Localization.Shell.Navigation.ComingSoon";
        public static readonly string PhotoStudio = "Localization.Shell.Navigation.PhotoStudio";
        public static readonly string Planned = "Localization.Shell.Navigation.Planned";
        public static readonly string Settings = "Localization.Shell.Navigation.Settings";
        public static readonly string SmartCutout = "Localization.Shell.Navigation.SmartCutout";
        public static readonly string Toolbox = "Localization.Shell.Navigation.Toolbox";
        public static readonly string Workspace = "Localization.Shell.Navigation.Workspace";
    }

    public static class Window
    {
        public static readonly string Subtitle = "Localization.Shell.Window.Subtitle";
        public static readonly string Title = "Localization.Shell.Window.Title";
        public static readonly string WorkbenchSubtitle = "Localization.Shell.Window.WorkbenchSubtitle";
    }
}

namespace Localization.PhotoStudio
{
    public static class Backgrounds
    {
        public static readonly string Blue = "Localization.PhotoStudio.Backgrounds.Blue";
        public static readonly string BlueName = "Localization.PhotoStudio.Backgrounds.BlueName";
        public static readonly string Custom = "Localization.PhotoStudio.Backgrounds.Custom";
        public static readonly string GrayDarkName = "Localization.PhotoStudio.Backgrounds.GrayDarkName";
        public static readonly string GrayLightName = "Localization.PhotoStudio.Backgrounds.GrayLightName";
        public static readonly string RedName = "Localization.PhotoStudio.Backgrounds.RedName";
        public static readonly string White = "Localization.PhotoStudio.Backgrounds.White";
        public static readonly string WhiteName = "Localization.PhotoStudio.Backgrounds.WhiteName";
    }

    public static class Labels
    {
        public static readonly string BackgroundHint = "Localization.PhotoStudio.Labels.BackgroundHint";
        public static readonly string Dpi = "Localization.PhotoStudio.Labels.Dpi";
        public static readonly string FileFormat = "Localization.PhotoStudio.Labels.FileFormat";
        public static readonly string Filename = "Localization.PhotoStudio.Labels.Filename";
        public static readonly string FilenameTemplate = "Localization.PhotoStudio.Labels.FilenameTemplate";
        public static readonly string HeightMm = "Localization.PhotoStudio.Labels.HeightMm";
        public static readonly string OutputQuality = "Localization.PhotoStudio.Labels.OutputQuality";
        public static readonly string SaveLocation = "Localization.PhotoStudio.Labels.SaveLocation";
        public static readonly string SizeHint = "Localization.PhotoStudio.Labels.SizeHint";
        public static readonly string SourceHint = "Localization.PhotoStudio.Labels.SourceHint";
        public static readonly string WidthMm = "Localization.PhotoStudio.Labels.WidthMm";
    }

    public static class Page
    {
        public static readonly string BackgroundSection = "Localization.PhotoStudio.Page.BackgroundSection";
        public static readonly string BackgroundSmartDescription = "Localization.PhotoStudio.Page.BackgroundSmartDescription";
        public static readonly string BackgroundSmartTitle = "Localization.PhotoStudio.Page.BackgroundSmartTitle";
        public static readonly string Breadcrumb = "Localization.PhotoStudio.Page.Breadcrumb";
        public static readonly string CompareOriginal = "Localization.PhotoStudio.Page.CompareOriginal";
        public static readonly string EngineReady = "Localization.PhotoStudio.Page.EngineReady";
        public static readonly string ExportImage = "Localization.PhotoStudio.Page.ExportImage";
        public static readonly string FitToWindow = "Localization.PhotoStudio.Page.FitToWindow";
        public static readonly string Help = "Localization.PhotoStudio.Page.Help";
        public static readonly string LivePreview = "Localization.PhotoStudio.Page.LivePreview";
        public static readonly string LoadImage = "Localization.PhotoStudio.Page.LoadImage";
        public static readonly string MoreSizes = "Localization.PhotoStudio.Page.MoreSizes";
        public static readonly string OutputHint = "Localization.PhotoStudio.Page.OutputHint";
        public static readonly string OutputSection = "Localization.PhotoStudio.Page.OutputSection";
        public static readonly string OutputSize = "Localization.PhotoStudio.Page.OutputSize";
        public static readonly string OutputSettings = "Localization.PhotoStudio.Page.OutputSettings";
        public static readonly string ResetView = "Localization.PhotoStudio.Page.ResetView";
        public static readonly string RotateLeft = "Localization.PhotoStudio.Page.RotateLeft";
        public static readonly string RotateRight = "Localization.PhotoStudio.Page.RotateRight";
        public static readonly string SizeSection = "Localization.PhotoStudio.Page.SizeSection";
        public static readonly string SmartCutoutComingSoon = "Localization.PhotoStudio.Page.SmartCutoutComingSoon";
        public static readonly string SourceSection = "Localization.PhotoStudio.Page.SourceSection";
        public static readonly string FlipHorizontal = "Localization.PhotoStudio.Page.FlipHorizontal";
        public static readonly string Guides = "Localization.PhotoStudio.Page.Guides";
        public static readonly string ThemeSwitch = "Localization.PhotoStudio.Page.ThemeSwitch";
    }

    public static class Sizes
    {
        public static readonly string Custom = "Localization.PhotoStudio.Sizes.Custom";
        public static readonly string OneInch = "Localization.PhotoStudio.Sizes.OneInch";
        public static readonly string SmallTwoInch = "Localization.PhotoStudio.Sizes.SmallTwoInch";
        public static readonly string TwoInch = "Localization.PhotoStudio.Sizes.TwoInch";
    }

    public static class Status
    {
        public static readonly string OutputPathMissing = "Localization.PhotoStudio.Status.OutputPathMissing";
        public static readonly string PreviewFailed = "Localization.PhotoStudio.Status.PreviewFailed";
        public static readonly string PreviewGenerated = "Localization.PhotoStudio.Status.PreviewGenerated";
        public static readonly string Ready = "Localization.PhotoStudio.Status.Ready";
        public static readonly string Reset = "Localization.PhotoStudio.Status.Reset";
        public static readonly string SaveFailed = "Localization.PhotoStudio.Status.SaveFailed";
        public static readonly string SavedFormat = "Localization.PhotoStudio.Status.SavedFormat";
        public static readonly string SourceImageNotFound = "Localization.PhotoStudio.Status.SourceImageNotFound";
        public static readonly string SourcePathRequired = "Localization.PhotoStudio.Status.SourcePathRequired";
        public static readonly string SourceSelected = "Localization.PhotoStudio.Status.SourceSelected";
    }

    public static class Summary
    {
        public static readonly string BackgroundFormat = "Localization.PhotoStudio.Summary.BackgroundFormat";
        public static readonly string NoImageSelected = "Localization.PhotoStudio.Summary.NoImageSelected";
        public static readonly string ProcessingFormat = "Localization.PhotoStudio.Summary.ProcessingFormat";
        public static readonly string SavedFormat = "Localization.PhotoStudio.Summary.SavedFormat";
    }
}

namespace Localization.Settings
{
    public static class Descriptions
    {
        public static readonly string AccentColor = "Localization.Settings.Descriptions.AccentColor";
        public static readonly string AutoCheckUpdate = "Localization.Settings.Descriptions.AutoCheckUpdate";
        public static readonly string CurrentVersion = "Localization.Settings.Descriptions.CurrentVersion";
        public static readonly string DefaultDpi = "Localization.Settings.Descriptions.DefaultDpi";
        public static readonly string DefaultFormat = "Localization.Settings.Descriptions.DefaultFormat";
        public static readonly string DefaultQuality = "Localization.Settings.Descriptions.DefaultQuality";
        public static readonly string DefaultSaveLocation = "Localization.Settings.Descriptions.DefaultSaveLocation";
        public static readonly string EmbedSrgb = "Localization.Settings.Descriptions.EmbedSrgb";
        public static readonly string FilenameTemplate = "Localization.Settings.Descriptions.FilenameTemplate";
        public static readonly string Language = "Localization.Settings.Descriptions.Language";
        public static readonly string OpenSourceRepository = "Localization.Settings.Descriptions.OpenSourceRepository";
        public static readonly string ProcessingEngine = "Localization.Settings.Descriptions.ProcessingEngine";
        public static readonly string ShowGuides = "Localization.Settings.Descriptions.ShowGuides";
        public static readonly string Theme = "Localization.Settings.Descriptions.Theme";
    }

    public static class Labels
    {
        public static readonly string AccentColor = "Localization.Settings.Labels.AccentColor";
        public static readonly string AutoCheckUpdate = "Localization.Settings.Labels.AutoCheckUpdate";
        public static readonly string CurrentVersion = "Localization.Settings.Labels.CurrentVersion";
        public static readonly string DefaultDpi = "Localization.Settings.Labels.DefaultDpi";
        public static readonly string DefaultFormat = "Localization.Settings.Labels.DefaultFormat";
        public static readonly string DefaultQuality = "Localization.Settings.Labels.DefaultQuality";
        public static readonly string DefaultSaveLocation = "Localization.Settings.Labels.DefaultSaveLocation";
        public static readonly string EmbedSrgb = "Localization.Settings.Labels.EmbedSrgb";
        public static readonly string FilenameTemplate = "Localization.Settings.Labels.FilenameTemplate";
        public static readonly string ImageProcessing = "Localization.Settings.Labels.ImageProcessing";
        public static readonly string Language = "Localization.Settings.Labels.Language";
        public static readonly string OpenSourceRepository = "Localization.Settings.Labels.OpenSourceRepository";
        public static readonly string ProcessingEngine = "Localization.Settings.Labels.ProcessingEngine";
        public static readonly string ShowGuides = "Localization.Settings.Labels.ShowGuides";
        public static readonly string Theme = "Localization.Settings.Labels.Theme";
    }

    public static class Options
    {
        public static readonly string Amber = "Localization.Settings.Options.Amber";
        public static readonly string AuroraCyan = "Localization.Settings.Options.AuroraCyan";
        public static readonly string Dark = "Localization.Settings.Options.Dark";
        public static readonly string Green = "Localization.Settings.Options.Green";
        public static readonly string Light = "Localization.Settings.Options.Light";
        public static readonly string NebulaPurple = "Localization.Settings.Options.NebulaPurple";
        public static readonly string SimplifiedChinese = "Localization.Settings.Options.SimplifiedChinese";
        public static readonly string System = "Localization.Settings.Options.System";
        public static readonly string TechBlue = "Localization.Settings.Options.TechBlue";
        public static readonly string TraditionalChinese = "Localization.Settings.Options.TraditionalChinese";
    }

    public static class Page
    {
        public static readonly string Appearance = "Localization.Settings.Page.Appearance";
        public static readonly string AutoSaved = "Localization.Settings.Page.AutoSaved";
        public static readonly string Breadcrumb = "Localization.Settings.Page.Breadcrumb";
        public static readonly string Exporting = "Localization.Settings.Page.Exporting";
        public static readonly string ImageProcessing = "Localization.Settings.Page.ImageProcessing";
        public static readonly string Subtitle = "Localization.Settings.Page.Subtitle";
        public static readonly string UpdateAbout = "Localization.Settings.Page.UpdateAbout";
    }
}

namespace Localization.Batch
{
    public static class Descriptions
    {
        public static readonly string Concurrency = "Localization.Batch.Descriptions.Concurrency";
        public static readonly string FilenameTemplate = "Localization.Batch.Descriptions.FilenameTemplate";
        public static readonly string OpenFolderWhenDone = "Localization.Batch.Descriptions.OpenFolderWhenDone";
        public static readonly string SkipProcessed = "Localization.Batch.Descriptions.SkipProcessed";
    }

    public static class Labels
    {
        public static readonly string Background = "Localization.Batch.Labels.Background";
        public static readonly string ChooseFile = "Localization.Batch.Labels.ChooseFile";
        public static readonly string Concurrency = "Localization.Batch.Labels.Concurrency";
        public static readonly string DropDescription = "Localization.Batch.Labels.DropDescription";
        public static readonly string DropTitle = "Localization.Batch.Labels.DropTitle";
        public static readonly string ExportAll = "Localization.Batch.Labels.ExportAll";
        public static readonly string ExportZip = "Localization.Batch.Labels.ExportZip";
        public static readonly string FilenameTemplate = "Localization.Batch.Labels.FilenameTemplate";
        public static readonly string File = "Localization.Batch.Labels.File";
        public static readonly string FollowOriginal = "Localization.Batch.Labels.FollowOriginal";
        public static readonly string KeepRatio = "Localization.Batch.Labels.KeepRatio";
        public static readonly string OpenFolderWhenDone = "Localization.Batch.Labels.OpenFolderWhenDone";
        public static readonly string Processing = "Localization.Batch.Labels.Processing";
        public static readonly string QueueHint = "Localization.Batch.Labels.QueueHint";
        public static readonly string QueueTitle = "Localization.Batch.Labels.QueueTitle";
        public static readonly string Remove = "Localization.Batch.Labels.Remove";
        public static readonly string SelectedCount = "Localization.Batch.Labels.SelectedCount";
        public static readonly string Size = "Localization.Batch.Labels.Size";
        public static readonly string SkipProcessed = "Localization.Batch.Labels.SkipProcessed";
        public static readonly string Status = "Localization.Batch.Labels.Status";
        public static readonly string UniformBackground = "Localization.Batch.Labels.UniformBackground";
        public static readonly string UniformSize = "Localization.Batch.Labels.UniformSize";
        public static readonly string UniformSizeTitle = "Localization.Batch.Labels.UniformSizeTitle";
    }

    public static class Page
    {
        public static readonly string AddImage = "Localization.Batch.Page.AddImage";
        public static readonly string AdvancedOptions = "Localization.Batch.Page.AdvancedOptions";
        public static readonly string Breadcrumb = "Localization.Batch.Page.Breadcrumb";
        public static readonly string PlannedDesign = "Localization.Batch.Page.PlannedDesign";
        public static readonly string Subtitle = "Localization.Batch.Page.Subtitle";
    }

    public static class Status
    {
        public static readonly string Completed = "Localization.Batch.Status.Completed";
        public static readonly string Failed = "Localization.Batch.Status.Failed";
        public static readonly string Processing = "Localization.Batch.Status.Processing";
        public static readonly string Waiting = "Localization.Batch.Status.Waiting";
    }
}
